SHOW WAREHOUSES; 

CREATE WAREHOUSE demo_warehouse
WITH 
WAREHOUSE_SIZE = "X-Small"
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = TRUE
COMMENT = "Demo warehouse created through a worksheet"

SHOW WAREHOUSES; 

ALTER WAREHOUSE COMPUTE_WH
SET AUTO_SUSPEND = 60; 

ALTER WAREHOUSE demo_warehouse
SET MAX_CLUSTER_COUNT = 3; 

DROP WAREHOUSE  DEMO_WAREHOUSE; 

SHOW WAREHOUSES;