SHOW WAREHOUSES; 

USE WAREHOUSE TEST_WH; 
SHOW DATABASES; 

USE U_S_ZIP_CODE_METADATA;

SHOW SCHEMAS ;

SHOW views IN SCHEMA INFORMATION_SCHEMA; 
SHOW tables IN SCHEMA ZIP_DEMOGRAPHICS; 



SHOW TABLES IN SCHEMA U_S_ZIP_CODE_METADATA.ZIP_DEMOGRAPHICS;

SELECT * 
FROM U_S_ZIP_CODE_METADATA.ZIP_DEMOGRAPHICS.ZIP_CODE_METADATA;


SELECT * 
FROM U_S_ZIP_CODE_METADATA.INFORMATION_SCHEMA.VIEWS;


SELECT DISTINCT(ZIP)
FROM ZIP_DEMOGRAPHICS.ZIP_CODE_METADATA;